name: Test and build

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run tests
        run: go test .

  release:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build linux amd64
        run: GOOS=linux GOARCH=amd64 go build -o bin/flowai-proxy_${{ github.ref_name }}_linux_amd64

      - name: Build linux arm
        run: GOOS=linux GOARCH=arm go build -o bin/flowai-proxy_${{ github.ref_name }}_linux_arm64

      - name: Build darwin amd64
        run: GOOS=darwin GOARCH=amd64 go build -o bin/flowai-proxy_${{ github.ref_name }}_darwin_amd64

      - name: Build darwin arm
        run: GOOS=darwin GOARCH=arm64 go build -o bin/flowai-proxy_${{ github.ref_name }}_darwin_arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/flowaicom/webhook-proxy
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          files: |
            README.md
            bin/*

